<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tides</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/sass/main.scss">
</head>
<body class="container">

    <h1>Weather</h1>

    <!-- section 1 --- tides -->
    <section>
        <h2>Weather</h2>



    </section>

    <!-- section 2 --- moon -->
    
</body>
</html>